[package]
name = "audioadapter-compat-audio"
version = "1.0.0"
edition = "2024"
rust-version = "1.87"
authors = ["HEnquist <henrik.enquist@gmail.com>"]
description = "audioadapter trait implementations for buffers from the `audio` crate"
license = "MIT OR Apache-2.0"
repository = "https://github.com/HEnquist/audioadapter-rs"
keywords = ["audio", "buffer", "dsp", "sample", "pcm"]
categories = ["multimedia::audio"]
readme = "README.md"

[dependencies]
audioadapter.workspace = true
audio-core.workspace = true

[dev-dependencies]
audio = "0.2.0"
