[package]
name = "audioadapter"
version = "4.0.0"
edition = "2024"
rust-version = "1.85"
authors = ["HEnquist <henrik.enquist@gmail.com>"]
description = "A library for making it easier to work with buffers of audio data"
license = "MIT OR Apache-2.0"
repository = "https://github.com/HEnquist/audioadapter-rs"
keywords = ["audio", "buffer", "dsp", "sample", "pcm"]
categories = ["multimedia::audio"]
readme = "README.md"

[features]
default = ["audio"]
audio = ["audio-core"]

test-utils = []

[dependencies]
num-traits.workspace = true
audio-core = { workspace = true, optional = true }

[dev-dependencies]
audio = "0.2.0"
criterion = "0.6"
num-traits = { workspace = true, features = ["std"] }

[[bench]]
name = "sqrt"
harness = false
