[package]
name = "audioadapter-buffers"
version = "4.0.0"
edition = "2024"
rust-version = "1.85"
authors = ["HEnquist <henrik.enquist@gmail.com>"]
description = "A selection of wrappers and buffers for audio data"
license = "MIT OR Apache-2.0"
repository = "https://github.com/HEnquist/audioadapter-buffers-rs"
keywords = ["audio", "buffer", "dsp", "sample", "pcm"]
categories = ["multimedia::audio"]
readme = "README.md"

[features]
default = ["std"]
std = ["audioadapter-sample/std", "num-traits/std", "alloc"]
alloc = []

[dependencies]
num-traits.workspace = true
audioadapter = { version = "4.0.0", path = "../audioadapter" }
audioadapter-sample = { version = "4.0.0", path = "../audioadapter-sample", default-features = false, features = ["audio"] }


[dev-dependencies]
criterion = "0.6"
audioadapter = { version = "4.0.0", path = "../audioadapter", features = ["test-utils"]}

[[bench]]
name = "iteration"
harness = false
required-features = ["alloc"]
