[package]
name = "audioadapter-sample"
version = "5.0.0"
edition = "2024"
rust-version = "1.87"
authors = ["HEnquist <henrik.enquist@gmail.com>"]
description = "A library for making it easier to work with audio data"
license = "MIT OR Apache-2.0"
repository = "https://github.com/HEnquist/audioadapter-sample-rs"
keywords = ["audio", "dsp", "sample", "pcm"]
categories = ["multimedia::audio"]
readme = "README.md"

[features]
default = ["std"]
std = ["num-traits/std"]

[dependencies]
num-traits.workspace = true

