[package]
name = "audioadapter-compat-dasp"
version = "1.0.0"
edition = "2024"
rust-version = "1.85"
authors = ["HEnquist <henrik.enquist@gmail.com>"]
description = "audioadapter trait implementations for dasp frame slices"
license = "MIT OR Apache-2.0"
repository = "https://github.com/HEnquist/audioadapter-rs"
keywords = ["audio", "buffer", "dsp", "dasp", "pcm"]
categories = ["multimedia::audio"]
readme = "README.md"

[dependencies]
audioadapter.workspace = true
dasp_frame.workspace = true
