on: [push, pull_request]

name: CI test and lint

jobs:
  check_test:
    name: Check and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Run cargo check
        run: cargo check --workspace --all-targets

      - name: Run cargo test
        run: cargo test --workspace --all-targets

      - name: Run rustdoc checks
        run: RUSTDOCFLAGS="-D warnings" cargo doc --workspace --all-features --no-deps

      - name: Compile benches
        run: cargo bench --workspace --no-run

      - name: Run cargo check no features
        run: cargo check --workspace --no-default-features

      - name: Run cargo check no features all targets
        run: cargo check --workspace --all-targets --no-default-features

      - name: Run cargo test no features
        run: cargo test --workspace --no-default-features

  publish_dry_run:
    name: Publish dry-run (${{ matrix.package }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [audioadapter, audioadapter-buffers, audioadapter-sample]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo publish dry-run
        run: cargo publish --dry-run -p ${{ matrix.package }}

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
